### ISSUE TITLE
void loop()でrgbを何回も宣言しているのが原因では？

### ISSUE THREAD

**Issue by aj1m0n** [keigo9/m5-neopixel#1]

**Comment by aj1m0n** [comment]
```
ありがとうございます:おじぎ_男性:
rabの宣言は見落としてました。
削除しても、挙動は変わらずでした。
```

serial.printlnしてみると電源は落ちていませんでした．

**Comment by aj1m0n** [comment]
回路とはM5とNeopixelがどのように繋がっていたかを知りたかっだけです
電流が足りずに電圧降下が発生している可能性があるかもしれないと思ったからです．

9軸の処理を後回しにして，neopixelの処理だけを行うプログラムを書き込んでてはどうでしょう？
それでも落ちますか？

**Comment by keigo9** [comment]
接続はGrovo線で直接繋いでいます。

最初は自分も、Core2の性能以上に電流をかけてしまっているからだと思いました。
しかし、UIFlowから書き込みを行なったプログラムは問題なく動作するので、Arduinoプログラム側の問題だと思いました。

9軸処理を後回しというのは、センサによって光らせ方を変化させないということでしょうか？
その場合、Neopixelを光らせる+9軸センサ値取得なら問題なく動作します。

**Comment by keigo9** [comment]
bugfix/power down
関数の切り出し、コードを見やすくした
brightnessを落とした
if分のelse処理をやめた
color(255,255,255)は謎に落ちる

電源供給状態では落ちなくなった。
